/* configure.c - determine configuration

   This file is part of yalloc, yet another memory allocator with emphasis on efficiency and compactness.

   SPDX-FileCopyrightText: © 2024 Joris van der Geer
   SPDX-License-Identifier: GPL-3.0-or-later

*/

#include <limits.h>
#include <stdarg.h>
#include <time.h>

#include <stdio.h>

#include "base.h"

#include "os.h"

#define _Sys_Page 12
#include "config.h"

#include "printf.h"

static int _Printf(2,3) error(ub4 line,cchar *fmt,...);

static int usage(void) {
  error(0,"usage: genadm <layout_file>");
  return 1;
}

#define Buffer 1024

static ub4 pagesize,page;

static char linorgbuf[Buffer];
static char linorgsbuf[Buffer];
static char accorgbuf[Buffer];
static char accorgsbuf[Buffer];

static ub4 linorgspos,accorgspos;

static ub4 linesizes[Maxorder+1];
static ub4 accsizes[Maxorder+1];

static void genmap(ub2 order,FILE *fp)
{
  ub2 ord;

  ub4 linorg = 0;
  ub2 acc;
  ub4 len,alen;
  ub4 linlen = 0;
  ub4 linorgpos,accorgpos;
  char *comma,*newline;

  if (order > 5) {
    len = 1U << (order - 6);
  } else len = 1;

  // Prepare line origins
  linorgpos = snprintf_mini(linorgbuf,0,Buffer,"static const ub4 _linorg%u[] = { ",order);
  accorgpos = snprintf_mini(accorgbuf,0,Buffer,"static const ub2 _accorg%u[] = { ",order);

  comma = order > Minregion ? "," : "";
  linorgspos += snprintf_mini(linorgsbuf,linorgspos,Buffer,"%s_linorg%u",comma,order);
  accorgspos += snprintf_mini(accorgsbuf,accorgspos,Buffer,"%s_accorg%u",comma,order);

  for (ord = Minorder; ord < min(order,Maxorder - Addorder); ord++) {
    comma = ord > Minorder ? "," : "";
    newline = ((ord - Minorder) & 7) == 7 ? "\n  " : "";
    if (order - ord < 4) newline = "";
    linorgpos += snprintf_mini(linorgbuf,linorgpos,Buffer,"%s%s%#x",comma,newline,linorg);

    linorg += max(1,len * 2); len >>= 1;
    if (ord == Minorder) linesizes[order] = linorg;
  }
  linlen = linorg;

  if (order > 11) {
    len = 1U << (order - 12);
  } else len = 1;

  for (ord = Minorder; ord < min(order,Maxorder - Addorder); ord++) {

    comma = ord > Minorder ? "," : "";
    newline = ((ord - Minorder) & 3) == 3 ? "\n  " : " ";
    if (order - ord < 2) newline = " ";

    accorgpos += snprintf_mini(accorgbuf,accorgpos,Buffer,"%s%s",comma,newline);
    alen = len;
    for (acc = 0; acc < Accel_cnt; acc++) {
      comma = acc  ? "," : "";
      accorgpos += snprintf_mini(accorgbuf,accorgpos,Buffer,"%s%#x",comma,linorg);
      linorg += max(1,alen);
      alen >>= 6;
    }

    if (ord == Minorder) {
      accsizes[order] = linorg - linlen;
    }
    len >>= 1;

  }

  linorgpos += snprintf_mini(linorgbuf,linorgpos,Buffer," }; // %u`\n",linorg);

  fprintf(fp,"%s\n%s };\n\n",linorgbuf,accorgbuf);

  // printf("genmap %u\n%s\n",order,linorgbuf);
}

static int _Printf(2,3) error(ub4 line,cchar *fmt,...)
{
  va_list ap;
  ub4 n = 0;
  char buf[256];

  if (line) n = snprintf_mini(buf,0,250,"Error genadm.c:%u - ",line);

  va_start(ap,fmt);
  n += mini_vsnprintf(buf,n,250,fmt,ap);
  va_end(ap);

  buf[n++] = '\n';
  fwrite(buf,1,n,stderr);
  return 1;
}

static void header(FILE *fp,cchar *name,cchar *name2,cchar *desc,char *timestr)
{
  fprintf(fp,"/* %s - %s for yalloc\n\n  Generated by genadm at %s\n\n",name,desc,timestr);
  fprintf(fp,"  based on config.h\n");
  if (name2) fprintf(fp,"\n  template: %s",name2);
  fputs(" */\n\n",fp);
}

#ifndef Page_override
static int genconfig(cchar *name,char *timbuf)
{
  FILE *fp;

  pagesize = ospagesize();
  if (pagesize == 0) {
    error(__LINE__,"Cannot get pagesize: %m");
    pagesize = 4096;
  }
  page = ctz(pagesize);

  fp = fopen(name,"w");
  if (!fp) return error(__LINE__, "cannot create '%s': %m",name);

  header(fp,name,nil,"generated config",timbuf);

  fprintf(fp,"#define _Sys_Page %u\n",page);

  fclose(fp);
  return 0;
}
#endif

int main(int argc,char *argv[])
{
  ub2 ord;
  FILE *fp,*dirfp;
  cchar *layoutname;
  char timebuf[256];
  char bck[2048];
  struct tm *nowtm;
  time_t now;
  size_t nread;
  cchar *comma;

  if (argc < 1) return usage();

  layoutname = argv[1];

  now = time(NULL);
  nowtm = gmtime(&now);
  strftime(timebuf,256,"%a %e %b %R UTC",nowtm);

#if defined Page_override && Page_override > 4
  sassert(Page_override < 32,"Page_override needs to be a power of two");
  page = Page_override;
  pagesize = 1u << pagesize;
#else
  if (genconfig("config_gen.h",timebuf)) return 1;
#endif

  snprintf_mini(bck,0,2048,"%s.bak",layoutname);
  rename(layoutname,bck);
  fp = fopen(layoutname,"w");
  if (!fp) return error(__LINE__, "cannot create '%s': %m",layoutname);

  header(fp,layoutname,nil,"admin layout",timebuf);

  fprintf(fp,"  Minorder %u  Maxorder %u  Minregion %u  Maxregion %u\n\n",Minorder,Maxorder,Minregion,Maxregion);

  for (ord = Minregion; ord <= Maxregion; ord++) {
    genmap(ord,fp);
  }

  fprintf(fp,"static const ub4 *linorgs = { %s };\n",linorgsbuf);
  fprintf(fp,"static const ub4 *accAorgs = { %s };\n\n",accorgsbuf);

  fprintf(fp,"static const ub4 buddy_linesizes[] = { ");
  for (ord = Minregion; ord <= Maxregion; ord++) {
    comma = ord == Minregion ? "" : ",";
    fprintf(fp,"%s%#x",comma,linesizes[ord]);
  }
  fputs("};\n",fp);
  fprintf(fp,"static const ub4 buddy_accsizes[] = { ");
  for (ord = Minregion; ord <= Maxregion; ord++) {
    comma = ord == Minregion ? "" : ",";
    fprintf(fp,"%s%#x",comma,accsizes[ord]);
  }
  fputs("};\n",fp);

  fclose(fp);

  printf("generated %s\n",layoutname);

  return 0;
}
